spring.application.name=mini-erp-backend

# Configuraci\u00f3n de Conexi\u00f3n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/minierp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n complementaria para JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
